### ISSUE TITLE
Week 8 - Proposed structure for Express and Handlebars week

### ISSUE THREAD

**Issue by PiotrBerebecki** [foundersandcoders/master-reference#295]
The deadline for developing week 8 materials is Friday, 4th August 2017.

## Tasks to complete: 

- [x] create learning outcomes file #462
- [x] create skeleton week schedule #463
- [x] create project brief #464
- [x] build workshop 1 - Intro to Express and middleware #465
- [x] build workshop 2 - Templating with Handlebars #466
- [x] build workshop 3 - Testing with an existing database, include continuous integration setup #467
- [x] build challenge 1 - Handlebars challenge #468
- [x] build challenge 2 - Accessible animated app drawer #469
- [x] create research topics file #470
- [x] create resources file #471

## Notes from previous SGCs that we should reflect in week 8

* Continue project from the previous week - we discussed this and decided against it as it would involve sections of the week on teaching auth in express, to be discuss with Alexis, Jessica and Ronan
* Update existing learning outcomes and make them concise and indicate what
  objectives are stretch goals.
* Give guidance on what is expected to be covered by research topics
* No front end testing
* Add a note that it is fine not to complete the project and re-iterate this to the cohort
* Workshop on setting up dev environment with CI, testing and coverage

**Comment by des-des** [comment]
HYPE: https://www.npmjs.com/package/express-engine-hotloader
