### ISSUE TITLE
Week 2 - Testing

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/master-reference#299]
## Testing Week

Mentors: @oliverjam | @finnhodgkin 
Main change: teach Tape instead of QUnit

**By the end of Sunday 25th June**

---

### Change introductory workshop to teach npm and Tape (UPDATE: intro to tape in workshop later)
As we're switching from QUnit to Tape students will need an introduction to npm and a brief overview of `module.exports`before we teach the Tape workshop (which shouldn't be too different to QUnit)
+ [x] create intro to npm #328
+ [x] change npm introduction to include tasks e.g. "install this module" https://github.com/foundersandcoders/npm-introduction/commit/690a9f16191a4b7c51bbda515de99685f9e161b6
+ [x] create readme on the TDD cycle #327
+ [x] complete readme on TDD cycle https://github.com/foundersandcoders/testing-tdd-intro
+ [ ] user-test `learn-tape` workshop

### ~~Use Tape for FizzBuzz workshop~~ UPDATE: workshop is being removed
~~This workshop needs to be changed to match Tape's syntax.~~

### Change Roman Numerals workshop into a code-along
Based on lots of feedback we're going to teach this as a TDD code-along. That way we aren't reliant on people knowing how to solve the actual problem and can just grasp the concept of TDD. We'll also incorporate some frontend here (HTML/CSS form to enter a number to convert).
+ [x] create code along repo (@oliverjam to create before weekend) #330
+ [ ] @finnhodgkin to user-test

### Change Waterfall workshop to an introduction to callbacks
+ [x] write callback morning challenge (@finnhodgkin) #331
+ [x] @oliverjam to user test

### Research Afternoon (UPDATE: topics are listed in the issue)
+ [x] add istanbul & async testing with tape to research topics #332

### DOM Manipulation workshop
Unchanged - everyone loved this

### Project: Todo App
Changed from stopwatch as we felt this didn't really fit the learning outcomes of learning how to test well. Everyone struggled with solving the actual problem for the majority of the project. Also the majority of our code wasn't particularly testable.

Instead we want to emulate the FACN1 Testing Project, which will provide some starter-code that is structured in a testable way. This has the added benefit of teaching students best practices in terms of structuring their code early on in the course.

+ [x] Tweak Eoin's Todo Project #310 
+ [ ] @finnhodgkin  to user-test once finished
+ [ ] @oliverjam to user-test once finished

### Slight edit to pure functions workshop
+ [x] examples in readme didn't full explain how to use solutions (@oliverjam) https://github.com/Jwhiles/pure-functions-easy-testing/issues/12

### Overview files
+ [ ] update resources file to include callbacks burger article #326 
+ [x] PR with changed learning outcomes (@oliverjam) #329
+ [x] PR with updates to schedule (PR from @finnhodgkin, additions from @oliverjam ) #346

**Comment by oliverjam** [comment]
# Testing Week Schedule

## Menu
 - [Learning outcomes](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-2/learning-outcomes.md)
 - [Research topics](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-2/research-afternoon.md)
 - [Project](https://github.com/foundersandcoders/master-reference/tree/master/coursebook/fragments/projects/tdd-todo)
 - [Resources](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-2/resources.md)

## Schedule

### Monday

- 10:00 - 11:00
[Intro to NPM](https://github.com/oliverjam/npm-introduction)
[Intro to testing and Tape](https://github.com/foundersandcoders/learn-qunit)
[Fizz Buzz](https://github.com/foundersandcoders/fizzbuzz)

- 11:00 - 13:00
[DWYL Test Driven Development (TDD) workshop](https://github.com/dwyl/learn-tdd)

— LUNCH —

- 14:00 - 16:00
[Roman numeral code-along](https://github.com/foundersandcoders/romanizer) - **to be edited**

- 16:00 - 18:00
Business development / community engagement

### Tuesday

- 10:00 - 11:00
Morning challenge - callbacks (TBC)

- 11:00 - 13:00
[Pure functions workshop](https://github.com/Jwhiles/pure-functions-easy-testing) as an introduction to testing things like stopwatches 😉

— LUNCH —

- 14.00 - 16:30
[Research](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-2/research-afternoon.md)

- 16:30 - 17:30
Review and Present research topics

- 17:30 - 18:00
[Introduce Project](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-2/project.md)

### Wednesday

- 10:00 - 11:00
Morning challenge - [DOM manipulation](https://github.com/mantagen/DOM-manipulation-Challenge)

- 11:00 - 13:00
Start projects

— LUNCH —

- 14:00 - 17:00
Projects

- 17:00 - 18:00
Speaker slot (previously [Gaza Sky Geeks](https://gazaskygeeks.com/) talk)

### Thursday

- 10:00 - 13:00
Projects

— LUNCH —

- 14:00 - 17:00
Projects

- 17:00 - 18:00
Speaker slot (previously [Huw Davies](https://github.com/hdrdavies) talk on testing)

### Friday

- 10:00 - 11:00
[Code review](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/code-reviews.md)

- 11:00 - 13:00
Respond to issues

— LUNCH —

- 14:00 - 14:45
Group stop-go-continue

- 14:45 - 17:00
Present projects

- 17:00 - 18:00
Team stop-go-continue

**Comment by jsms90** [comment]
By the end of Sunday 25th:
+ [ ] PR with changed learning outcomes (@oliverjam)
  + remove QUnit, add learning tape, add learning what npm is
  + remove reference to waterfall functions, add callbacks
+ [ ] user test `learn-tape` workshop (@finnhodgkin responsible for raising issues + @oliverjam)
+ [ ] change Roman Numeral workshop into code along (@oliverjam to create before weekend, @finnhodgkin & @jsms90 to user test over weekend)
  + [ ] write learning outcomes
  + [ ] add UI - to combat confusion over DOM manipulation
+ [ ] write callback morning challenge (@finnhodgkin to write, @oliverjam & @jsms90 to user test)
+ [ ] PR with new research topics (@oliverjam)
+ [ ] small edit to pure functions workshop - examples in readme didn't full explain how to use solutions (@oliverjam)
+ [ ] todo project
  + [ ] write user stories, including the way the UI should be e.g. specify that you need an accessible form (@oliverjam)
  + [ ] add test file (@finnhodginn)
  + [ ] "user test" - attempt this project yourselves (@oliverjam @finnhodgkin), check contents of skeleton
+ [ ] PR for updating week schedule (@finnhodgkin)
  + [ ] remove fizz buzz workshop from schedule
  + [ ] replace QUnit workshop with DWYL's `learn-tape` workshop

**Comment by jsms90** [comment]
New time estimate from @oliverjam

To be finished by the end of Thursday 29th June:
#327 #310 #330 https://github.com/Jwhiles/pure-functions-easy-testing/issues/12 #346

I will look into alternatives for "async testing" so that #332 can be finished and its PR merged

Oli, please ask @finnhodgkin if you need any support :+1:

**Comment by oliverjam** [comment]
@jsms90 I think they're all done, just before midnight 😉 

Just waiting for PRs to be merged, assuming there are no more issues with them.

**Comment by jsms90** [comment]
@oliverjam @finnhodgkin Have you user tested each other's workshops and/or had other people user test them? (see the checkboxes)
