### ISSUE TITLE
Week3 API week planning and updates

### ISSUE THREAD

**Issue by edgarfinn** [foundersandcoders/master-reference#300]
Deadline for final plans: Friday 30th June

The week generally received positive feedback. Day 1 workshops were really well received. We just plan to really solidify familiarity with these challenges / workshops to ensure we can deliver them the best we can.

#### Additions and clarifications of the learning outcomes (Edgar)
(#340)
- [x] How to implement a parallel functions.
- [x] Introduction to the concept of and importance of software architecture: file structure planning, white-boarding an app, IIFEs

The Architecture and Parallel functions workshops / challenges are our main areas of focus.

#### @eliascodes' [stackexchange profile builder workshop](https://github.com/foundersandcoders/workshop-client-side-design), on code architecture and planning (Lucy & Elias)
Students found it a bit complicated and verbose.

Split this workshop into two much smaller workshops, totalling just half a day (instead of a whole day):
- [x] (#317) White-board planning workshop: enforcing pen + paper/whiteboard planning of an app's file structure. Introducing pseudo-code flow-charts. (Lucy)
- [x] (#336) Modular design workshop: Introducing IIFEs, closures and modular design patterns by providing students with a function (but non-modular) code base of a basic app, and asking them to break it out into modules. (Elias)

#### Revert to using @besarthoxhaj's [Parallel functions morning challenge](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-3/morning-challenge.md), as completed by FaCN1....but with a few tweeks to make it a bit more manageable (Edgar)

This was a valuable and greatly appreciated morning challenge, but students struggled a little with the task at hand. 
- [x] (#337) Simply add some comments and clarity in the readme and code to ensure the challenge is totally clear and the codebase is as readable as possible. 

#### Introduce a Front-end skills (flexbox) workshop (Martha)
- [x] (#339) Filling the half-day we've freed once we've reduced the architecture workshop, we want to introduce a flex-box layout workshop. Introducing students to the wonderful world of flexbox, and challenging them to design a simple responsive app using provided images / content.

#### Github API workshop (Edgar)
- [x] User-test github api workshop and make sure its possible to complete without waterfall functions. If WF necessary. The workshop will need refactoring

#### ~~Project~~
- ~~(#360) Based on the introduction of flexbox, we will add the requirement that students' projects this week use a responsive layout to present the results of their API calls which update the DOM~~

- [x] (#358) Update resources with relevant links (Edgar)
- [x] (#359) Update week 3's schedule (Lucy)

**Comment by jsms90** [comment]
### Day 1 meeting at 9.15am
+ [Mentor assignments to each workshop](https://github.com/foundersandcoders/master-reference/pull/448)
  + @JWLD has offered to help deliver the week :tada: 
+ Week schedule not finished yet
  + [This PR](https://github.com/foundersandcoders/master-reference/pull/409) needs to be closed / corrected, as per the requested changes
  + Waiting for a link to the flexbox workshop in the relevant issue #339 (@smarthutza)
  + Flexbox workshop is only 45mins-1hr & hasn't been user tested yet (ask @njsfield in person and post a link in the gitter channel)
  + With the current estimates for each workshop, there is still 1.5 hours of unfilled time
    + Flexbox froggy before @smarthutza's workshop?
    + Css diner after @smarthutza's workshop?
    + Re-introduce research afternoon?
    + Modular design workshop hasn't been user tested yet - how long does it take? (@smarthutza @JWLD @lucyrose93 to do this today in preparation for delivery tomorrow)

**Comment by lucyrose93** [comment]
@jsms90 @smarthutza @JWLD 
We have tested the modular design workshop. We think it would make a good basis for a research afternoon, instead of doing the workshop itself. See #450 
This means that we have a full schedule for the day :)

**Comment by lucyrose93** [comment]
@JWLD is now giving Elias' Software Design Workshop instead of the research afternoon. See #450. He has gone through the workshop and feels that it is worth delivering as is. He feels confident teaching it so I'm happy to support him in that and lend a hand of course. 

- [ ] Add Software design workshop instead of research afternoon to week's schedule.

FYI @smarthutza @jsms90

**Comment by jsms90** [comment]
Alumni who have user tested the flexbox workshop have so far given "15 minutes" as a time estimate of how long it takes to complete.

Flexbox froggy could take them 45 mins - 1 hour. But I think we're really pushing it to suggest that this might take 1hr45mins.

**Comment by mattlub** [comment]
@jsms90 There is also a fairly long resource which it says to read. I have also made an issue requesting more of an intro and some examples in the workshop- It should be made for absolute beginners, especially as there is no flexbox in the precourse/prereqs as far as I'm aware. I don't think 1h45 is that unreasonable, I guess there could be more steps if you complete the first bit?

**Comment by lucyrose93** [comment]
# Updated Schedule

10.00-11.00 Flexbox Froggy
11.00-11.30 Flexbox Dice Morning Challenge
11.45-13.00 Software Architecture
14.00-17.00 Software Design
17.00-18.00 Introduce Projects & Start Planning Your Architecture 

@JWLD @smarthutza @jsms90

**Comment by oliverjam** [comment]
The flexbox workshop took me 10-15 mins, but I have done tons of flexbox before, so didn't need to read any of the resources

**Comment by jsms90** [comment]
@mattlub Agreed, but it's a bit misleading to suggest that the workshop takes 1hr45mins when the largest portion of that time is taken up by completing external resources.

As @lucyrose93 has posted here, it seems more sensible to link students from the week schedule directly to those resources and timebox for their completion. Then each constituent part can be kept in or moved out of the week schedule without effecting each other.

**Comment by mattlub** [comment]
@lucyrose93 @jsms90 I still think it would be better to just improve the flexbox workshop slightly than just split it up, especially if you're scheduling them back-to-back

**Comment by jsms90** [comment]
@mattlub Any particular reason why you wouldn't split the workshop into "prerequisites" and actual content? This is essentially what is being suggested in issue #175 

Separating the material this way makes each ["part"](https://github.com/foundersandcoders/master-reference/blob/master/vision.md#implementation) individual and more composable. That way, someone could move the prerequisties into the precourse material (for example) and still keep the workshop itself. Or they could remove the workshop itself, but keep flexbox froggy.

**Comment by mattlub** [comment]
@jsms90 I agree there should be pre-reqs for workshops, I think I even raised that initially at a SGC. But that seems like a slightly different discussion. There is no flexbox on the course before this so it makes to me for it to be an introductory workshop.

I agree it could be split into a shorter introductory workshop and a 'challenge' part (the dice bit), I just feel that there should be more than just a link to flexbox froggy as an intro to flexbox.

Also with respect to the vision of the master ref, this is something I was aware of, but I was under the impression it wasn't being exactly followed seeing as though we don't have separate curriculums for the different campuses.

**Comment by jsms90** [comment]
> I agree it could be split into a shorter introductory workshop and a 'challenge' part (the dice bit), I just feel that there should be more than just a link to flexbox froggy as an intro to flexbox.

I'm just a little confused. The workshop itself also just contains links to these external resources as prerequisites. If you think that we should provide instructions for how to complete flexbox froggy, feel free to write an introductory workshop? :woman_shrugging: 

> Also with respect to the vision of the master ref, this is something I was aware of, but I was under the impression it wasn't being exactly followed seeing as though we don't have separate curriculums for the different campuses.

This is absolutely true. The vision is something we are not yet able to follow to the letter, but something we are aspiring to. Hence why I'm trying to ensure that each part is separable. If flexbox froggy and the dice workshop were inseparable, then I would agree that there would be no point in providing a separate link.

**Comment by mattlub** [comment]
@jsms90 yeh sure, maybe it will be enough- I guess see how it goes in London.

**Comment by jsms90** [comment]
@smarthutza @lucymonie @JWLD Happy to close this epic?

**Comment by lucyrose93** [comment]
@jsms90 Happy to close it, yes. I think it worked well to split up the Flexbox activities this week. Maybe @mattlub could try a different approach and let us know how it goes?
