### ISSUE TITLE
Week 5 - proposal for changes

### ISSUE THREAD

**Issue by joeylouise** [foundersandcoders/master-reference#304]
**DEADLINE FOR PRs - FRIDAY 14th JULY**

- [x] **Rethink scope of project #282 (pull request for changes #303) MAJA**
   - Contact Travis to ask whether we can increase no of concurrent builds for each new cohort organisation
<br>

- [x] **Remove / shorten Node shell scripting #274 JOEY**
    - ~~currently there are two lessons.~~
    - ~~Proposal to keep lesson 2, exercises 2a and 2b~~
    - ~~In exercise 2a, replace rewriting cat.js command with reading a file e.g. a book~~
    - ~~We expect this would take approx. 1 hr~~
    - ~~Replace the extra approx 2hrs with something else, e.g. a front end workshop / challenge~~
    - Remove notes from end of lesson1.md (https://github.com/foundersandcoders/Node-Shell-Workshop/issues/4)
    - Add public/ in paths to index.html and example.js (https://github.com/foundersandcoders/Node-Shell-Workshop/issues/7)
    - Rename read.extension and write.extension (https://github.com/foundersandcoders/Node-Shell-Workshop/issues/6)
    - Folder with solutions (https://github.com/foundersandcoders/Node-Shell-Workshop/issues/11)
    - Update week schedule link to node shell workshop #488 
 <br>

- [x] **Make sure all workshops work as expected #283 JOEY & MAJA**
    - run through all workshops, make sure they have solutions branches and that everything works as expected    
<br>

- [x] **Request module workshop MAJA**
    - no changes proposed, just suggest putting context around it so it's clear what is expected
    - https://github.com/RhodesPeter/request-module-workshop/issues/3
<br>

- [x] **Background reading #302 MAJA**
    - include background reading about streams for extra info
    - add resources in #302 to the Resources.md for the week 
<br>

- [x] **Error handling workshop** https://github.com/foundersandcoders/error-handling-workshop/
   - Solutions branch (https://github.com/foundersandcoders/error-handling-workshop/issues/3)
   - Context around example approaches (https://github.com/foundersandcoders/error-handling-workshop/issues/4)
   - Provding test cases (https://github.com/foundersandcoders/error-handling-workshop/issues/5)
   - Callback trap in example (https://github.com/foundersandcoders/error-handling-workshop/issues/8)
   - Add maintainer (https://github.com/foundersandcoders/error-handling-workshop/issues/9)
   - Contextualise the validation exercises with security issues (https://github.com/foundersandcoders/error-handling-workshop/issues/10)
<br>

- [x] **Shot and tape workshop JOEY**
  - We have made a few changes to make sure workshop works as expected 
Code doesn't work - Res needed instead of response
(https://github.com/foundersandcoders/tdd-node-server-with-shot-and-tape/issues/21)
npm start does not work as router is not defined
(https://github.com/foundersandcoders/tdd-node-server-with-shot-and-tape/issues/20)
<br>

- [x] **Research afternoon #446 JOEY**
  - Replace Code Coverage as this has now been covered in week 2
  - Suggestion --> make own npm module to e.g. interesting output for test failure / success (nyan cat) (look at end of @bradreeder node shell workshop)

**Comment by jsms90** [comment]
Guys, don't forget [the proposal that was passed](https://github.com/foundersandcoders/master-reference/issues/263) around spreading the assumed knowledge of OAuth week across the course. You guys should incude some server-side validation in this week.

You might want to think about making that a key part of the project?

**Comment by joeylouise** [comment]
Thanks @jsms90, yep, we've added server side validation as a requirement in the project spec (#303) and validation is covered in the error handling workshop. @eliascodes is amending the error handling workshop at the moment so we can review

**Comment by eliascodes** [comment]
@joeylouise @majakudlicka please see my pull requests foundersandcoders/error-handling-workshop#12 and foundersandcoders/error-handling-workshop#13

**Comment by joeylouise** [comment]
Remove / shorten Node shell scripting #274
- We will go through @bradreeder workshop and see what changes are needed
- Probably need to add context in the README about what node shell scripting is
- If we want to use @msachi version, need to speak to @msachi and @bradreeder 
- If we use @bradreeder version, need to update week schedule link to workshop

**Comment by joeylouise** [comment]
Rethink scope of project #282 (pull request for changes #303)

- Contact Travis to ask whether we can increase no of concurrent builds for each new cohort organisation

**Comment by jsms90** [comment]
@joeylouise @majakudlicka Excellent progress guys :grin: 

Please make sure you're closing your issues, in `master-reference` and in the separate repos, as and when you finish the work :+1:
