### ISSUE TITLE
Week 7 - planning authentication week

### ISSUE THREAD

**Issue by alexis-l8** [foundersandcoders/master-reference#305]
EDITED by Jen - raising granular issues instead of discussing everything about this week in one issue :+1: 

---

An authentication week is being created because of [this proposal](https://github.com/foundersandcoders/master-reference/issues/263).
 
Based on the [workflow for planning curriculum weeks](https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/planning-weeks.md#workflow) and the [ideal week structure](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/week-schedule.md), we need:
+ [ ] learning outcomes for the week #348 
+ [x] create week schedule #356
+ [x] a project brief #350
+ [x] an HTML/CSS morning challenge #351  
(to satisfy the "teach a lot more HTML/CSS" proposal #258)
+ [ ] another morning challenge (tbc) #352
+ [x] create workshops
  + [x] 1: password security - hashing & salting #349  
https://github.com/foundersandcoders/ws-password-management 
  + [x] 2: cookies & routing #354
  + [x] 3: session management (with cookies) #353  
https://github.com/foundersandcoders/ws-session-management
+ [x] 4 topics for research #355

#### JWT or not JWT?
![image](https://user-images.githubusercontent.com/15656538/27412424-63233edc-56ec-11e7-88f5-e93ec1f04a46.png)
![image](https://user-images.githubusercontent.com/15656538/27412512-09915a1a-56ed-11e7-9805-f6dbaea0acb3.png)
![image](https://user-images.githubusercontent.com/15656538/27412524-23c601ba-56ed-11e7-821c-ed635a1e99fd.png)
![image](https://user-images.githubusercontent.com/15656538/27412542-392a6636-56ed-11e7-8c2c-7b2b29c1018a.png)

### Background reading
https://www.quora.com/How-Session-and-Cookies-related
https://ponyfoo.com/articles/json-web-tokens-vs-session-cookies
http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/
http://by.jtl.xyz/2016/06/the-unspoken-vulnerability-of-jwts.html

**Comment by jsms90** [comment]
Updated the comment above to:
+ reflect the fact that we're not 100% clear on responsibilities yet
+ link to 2 new repos for the day 1 workshops
+ link to the existing JWT workshop (for now). We may want to reformulate this. I have a feeling we'll want to scrap it and create something more hands-on

**Comment by jsms90** [comment]
Reminder of past research topics

[FAC9 hapi Research topics](https://foundersandcoders.gitbooks.io/fac9/content/week5/readme_topics.html)
+ [Authentication](https://github.com/FAC9/READMES/blob/master/hapi/authentication.md)

[FAC9 - OAuth research day topics](https://foundersandcoders.gitbooks.io/fac9/content/week8/readme_topics.html)
+ [Authentication](https://github.com/FAC9/READMES/blob/master/oauth/authentication.md)
+ [Authorisation](https://github.com/FAC9/READMES/blob/master/oauth/authorisation.md)
+ [Cookies & local storage](https://github.com/FAC9/READMES/blob/master/oauth/cookies-and-local-storage.md)
+ [JWTs](https://github.com/FAC9/READMES/blob/master/oauth/jwts.md)

[FAC10 / FACN1 Research topics](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-7/research-afternoon.md) - 
  + Authentication (not in the FAC10's research repo) | [FACN1](https://github.com/FACN1/research/blob/master/week-7/authentication/authentication.md)
  + Cookies & caching - [FAC10](https://github.com/FAC10/research/blob/master/week-7/Cookies-and-Caching.md) | [FACN1](https://github.com/FACN1/research/blob/master/week-7/cookies/cookiesAndCaching.md)

[FACN1's week 8 research on JWTs](https://github.com/FACN1/research/blob/master/week-8/whatIsAJWT.md)

**Comment by jsms90** [comment]
Project brief:

Some kind of CMS whose users have different sets of permissions that affect route access

**Comment by des-des** [comment]
@jsms90 Do you think scope / granular permission might be too

**Comment by des-des** [comment]
@alexis-l8 @jsms90 @ronanyeah 

Should we add the idea of signing to the first workshop, since it relies on hashing..

**Comment by ronanyeah** [comment]
@des-des I'd like to keep 'password management' and 'session management' separate but I see where you are coming from. Maybe:
1. Intro to hashing
2. Password Management
3. Session Management

would be a better layout for day 1?

CC: @alexis-l8 @bo-bok @jsms90

**Comment by des-des** [comment]
@ronanyeah @alexis-l8 @bo-bok @jsms90 

I really do not know about this kind of stuff, but I think signing is important. Hapi-auth-cookie signs its contents: https://github.com/hapijs/hapi-auth-cookie. JWTs sign their contents. express-cookie signs its contents: https://github.com/expressjs/cookie-session.

I would say 
Monday
1: Hashing, signing and encryption.
2. Signup and login with hashed passwords.
3. Stateless session management (roll your own middleware that signs and verifies cookies).

I think the three important this missing are
1. JWTs (since the students should now understand how they work, maybe it is not important to keep this in the curriculum, since students are now better equipt to use these than they were before).
2. Stateful session management
3. Oauth, on that last one, I know we wanted to get rid of it, but in the real world, this is what a underfunded startup is going to use. There is also a strong security argument to outsource authentication (Although I would happily drop this argument in favour of not diverting the conversation here).

I actually thing Oauth should what the students spend day 2 doing. They could do
Tuesday morning. Stateful session management with redis (This might seem like a lot, but I think you could extend yesterdays solution (stateless session management) to use redis + some verify func in like 20 lines of code), we could gloss over lots of (essentually redis is a key value store - simple as f*), but mention its powerful pub/sub. Tuesday afternoon, github oauth.

This seems like loads of stuff, but I think we can put together 5 solid workshops that would cover all this, we could drop research afternoon ... Happy to create one of these myself.

Thoughts ?

**Comment by ronanyeah** [comment]
@des-des As excess 'glossing' is the reason that the last auth week is being scrapped entirely, and due the inherent importance of security/auth, I am completely against any of it AT ALL during this week.

I would much rather err on the side of 'less content, rigorously understood', and we can add stuff for the next round. Related to that, my only hard objection to your suggestions is the inclusion of stateful session management.

In the gitter channel you mentioned choosing 1 good way to do auth and focusing on that. I strongly believe that is the best way to go, and I am currently leaning towards a stateful JWT cookie being that solution. It is a solid solution, and most importantly, we can iterate towards it.

```
Hashing + safe password management ->
Cookie headers + insecure cookies ->
Signed naive user id cookies ->
Signed JWT cookie + encryption
```

As for OAuth, in an already busy week I think it is a distraction, and I would prefer that every team takes the same broad auth approach in their projects to enforce the understanding of its basic concepts, and so they can focus on its useful implementation instead, multiple access levels, secure routing etc. I totally agree with your startup comments etc but I think that is more of a justification for a post week 8 workshop if anything.

Overall, I don't think we can teach 'all of auth' successfully in a week, any more than we can teach 'all of design' successfully in front end week.

**Comment by des-des** [comment]
Sure, we can leave oauth / stateful stuff out. Those are fair enough points.

>  a stateful JWT cookie being that solution

You mean stateless?

I am easy, we need to make sure students understand the what and the why of the jwt spec

> Signed naive user id cookies ->
Signed JWT cookie + encryption

I would rather a username than id, but am easy.

Could you expand on
> Signed naive user id cookies



A jwt represents a set of claims, so here you are saying the claim would be `I am user with id: {id}`

> Signed JWT cookie + encryption

Also, I think it would be good to think about implementation here.
There are two options, Encrypted JWTs are a thing, I think that is in the spec, we could use a library that implements those, the problem there is that we are hiding a lot of the magic from the students.

Another option is to create a jwt using a jwt lib, then encrypt the result. Again all the jwt magic is hidden.

We could roll our own jwt lib, but we should mock this out and see how complicated it is first (obviously it will be for instructional purposes only).

The thing about using jwts is it leaves us with two options, 1. using a library, this will hide what is going on from the users, 2, implementing the jwt spec. I expect this adds complexity beyond just signing and encrypting a piece of json

**Comment by jsms90** [comment]
Love the additions above from both of you.

@des-des This sounds great:
1: Hashing, signing and encryption.
2. Signup and login with hashed passwords.
3. Stateless session management (roll your own middleware that signs and verifies cookies)

How would you divide these between 2 workshops?

**Comment by ronanyeah** [comment]
> You mean stateless?

Yes!

> Signed naive user id cookies

By that I mean if the user id is 5, the cookie will be `user_id=5.jhiejfei7656786` after hashing. That's pretty simplistic so then we could move to encrypted claims, or a JWT.

> 1. Hashing, signing and encryption.

Hashing and encryption, if i understand them correctly, have completely different uses, are not that closely related beyond 'they both change strings' and I think they should be taught separately. I am open to discussion.

Right so we need to discuss the session management more, but I am going to try and finish Workshop 1 ASAP as password management is well defined and isolated:

__Password Management Learning Outcomes (Workshop 1)__
- why not to store plaintext passwords
- what is hashing
- ineffective hashing vs bcrypt hashing
- how to use [bcryptjs](https://www.npmjs.com/package/bcryptjs)

**Comment by jsms90** [comment]
@ronanyeah Agreed. No need to go over encryption in this workshop

> A first thing to note is that there are many people who talk about encrypted passwords but really mean hashed passwords....In shorter words: if MD5 or SHA-1 is involved, this is password hashing, not password encryption. Let’s use the correct term.
[IT Community Security Blog](http://security.blogoverflow.com/2011/11/why-passwords-should-be-hashed/)

In this workshop we should explain hashing and salting. Bcrypt is perfect. I would add to the learning outcomes, that students should know about various kinds of attacks they're leaving their website susceptible to otherwise.

Useful article on this: [Password encryption hashing salting explained](https://thomashunter.name/blog/password-encryption-hashing-salting-explained/)

**Comment by jsms90** [comment]
@ronanyeah @alexis-l8 @des-des @bo-bok Based on what I've been doing with each of the mentor teams so far, I'm going to suggest that we split this issue up

You can see the pattern that I'm following for curriculum iterations here: #280 

We won't be able to do the exact same thing, because we're creating a week from scratch rather than iterating on existing material. But we can do something similar, and I'm keen for us not to [follow past mistakes by putting all of our week's planning in one issue](https://github.com/foundersandcoders/master-reference/issues/216#issuecomment-302720328)

**Comment by jsms90** [comment]
@des-des @ronanyeah Where did we land on
+ which 3 workshops are actually going to be created?
+ whether we're covering JWTs?

**Comment by ronanyeah** [comment]
Can someone give this a crack and see if it makes any sense? https://github.com/foundersandcoders/ws-password-management

**Comment by jsms90** [comment]
Still to go:
+ [ ] project brief PR should be ready to merge
+ [ ] week schedule - @bo-bok could you make the necessary changes to the existing PR so we can get that merged, now that we have all the repo links?
+ [ ] password workshop
  + [ ] @des-des weren't you going to submit a PR making it more interactive by using the terminal?
  + [ ] @alexis-l8 how's the password presentation coming along? can you make sure you put your slides in FAC Shared & pop a link into foundersandcoders/master-reference#349 please? :pray:
+ [ ] cookies workshop - needs solutions (@ronanyeah @alexis-l8?) & I have a few minor additions to make
+ [ ] session management - still a WIP
+ [ ] callbacks morning challenge - @des-des is [this](https://github.com/foundersandcoders/mc-do-this-then-do-that) the one? I've raised a bunch of issues

**Comment by ronanyeah** [comment]
@jsms90 I'll take solutions. I can also take interactive WS1.

**Comment by ronanyeah** [comment]
I am tossing out and rewriting WS3 for a new session management technique called JWX. It's where you put your cookie inside a signed react component inside an encrypted docker container. It's not that popular yet but its cool and the students deserve the best.

**Comment by des-des** [comment]
Yeah, I think soon you will be able to deploy the docker container directly in the browser with webassembly.

I think until webassembly / docker has been sorted we should hold off on JWX? Then we can do real serverless..

**Comment by ronanyeah** [comment]
Weren't WASM containers a week 3 morning challenge?

**Comment by des-des** [comment]
I think it got moved to pre-course
