### ISSUE TITLE
Week 6 – Proposal for changes

### ISSUE THREAD

**Issue by ConchobarMacNessa** [foundersandcoders/master-reference#308]
**Friday 21st July - Deadline**

We suggest the following changes to the Week 6 curriculum:

[pg workshop](https://github.com/foundersandcoders/pg-workshop) @pbywater
- [x] https://github.com/foundersandcoders/pg-workshop/issues/18 Add CSS component to workshop
- [x] https://github.com/foundersandcoders/pg-workshop/issues/19 Clarify instructions
- [x] https://github.com/foundersandcoders/pg-workshop/issues/20 Create solutions branch
- [x] https://github.com/foundersandcoders/pg-workshop/issues/21 Minor copy edits for clarity throughout
- [ ] Change name

 [db morning challenge](https://github.com/foundersandcoders/db-morning-challenge) @ConchobarMacNessa 
- [x] https://github.com/foundersandcoders/db-morning-challenge/issues/13 Change challenge from ElephantSQL to Heroku. 
- [x] https://github.com/foundersandcoders/db-morning-challenge/issues/14 Add expected solutions to readme. 
- [ ] Change name

Research topics: @ConchobarMacNessa 
- [x] #293 Clarify testing
- [x]  https://github.com/foundersandcoders/master-reference/issues/208 Clarify maintenance

Pgexercises @macintoshhelper 
- [ ] #291 Remove the exercises and add repo

[pg-walkthrough](https://github.com/foundersandcoders/pg-walkthrough) @macintoshhelper 
- [x] #290 Present this as a code along
- [ ] Change name
- [ ] Include SQL injection

Installation walkthrough @macintoshhelper 
- [x] #288 Refactor installation instructions

Projects @ConchobarMacNessa 
- [x] Remove elephantSQL suggestion from project intro https://github.com/foundersandcoders/master-reference/issues/445

Resources @macintoshhelper 
- [ ] Update resources file to include @macintoshhelper 's readmes or preexisting documentation that isn't awful

**Comment by jsms90** [comment]
@pbywater @ConchobarMacNessa @macintoshhelper to be done:
+ Setup instructions
  + PR to swap DWYL's postgres.app setup instructions for [Elias' setup readme](https://github.com/macintoshhelper/learn-sql/blob/master/postgresql/setup.md)
  + Mentors to user test
  + https://github.com/macintoshhelper/learn-sql/issues/4
+ Teaching SQL commands
  + PR to replace www.pgexercises.com with [Elias' SQL commands workshop](https://github.com/foundersandcoders/sql-commands-intro/blob/859f8edbdd237b2e09f76cf6b12525f6ca88e50b/README.md)
  + Mentors & alumni to user test
  + Review this PR https://github.com/foundersandcoders/sql-commands-intro/pull/1 and check it satisfies the open issues
  + Compare this new workshop to existing [afternoon workshop](https://github.com/foundersandcoders/postgres-workshop) that's coming right after it. Is there too much crossover? Does the afternoon one need to be adjusted at all?
+ [Afternoon workshop](https://github.com/foundersandcoders/postgres-workshop)
  + _If_ the morning's setup instructions are changing, the [set up instructions in this repo](https://github.com/foundersandcoders/postgres-workshop#set-up) need to be updated (didn't want to raise an issue yet, because I'm not sure if the setup is definitely being replaced)
  + Does this go into joins sufficiently, considering we don't have that research topic any more and FAC10 said the workshops were heavy on basic `SELECT` queries?
+ Code along
  + Two PRs to review once the changes have been made https://github.com/foundersandcoders/pg-walkthrough/pull/16 and https://github.com/foundersandcoders/pg-walkthrough/pull/17
  + Add tests https://github.com/foundersandcoders/pg-walkthrough/issues/18
+ Day 2 afternoon workshop
  + Review this PR https://github.com/foundersandcoders/pg-workshop/pull/22
  + Solutions folder instead of branch https://github.com/foundersandcoders/pg-workshop/issues/26
  + Handle errors https://github.com/foundersandcoders/pg-workshop/issues/27
+ Morning challenge
  + User tested by all 3 mentors
  + Fix issues https://github.com/foundersandcoders/db-morning-challenge/issues

**Comment by jsms90** [comment]
Updates from the list above:
+ Setup instructions :+1: - the PR is waiting for a second maintainer of the `master-reference` to merge
+ SQL commands - PR needs fixing & then a review from someone who has user tested the workshop
+ Afternoon workshop - no one has worked on [the outstanding issues](https://github.com/foundersandcoders/master-reference/issues/308#issuecomment-318898937) so I'll submit PRs tonight and you guys can review tomorrow
+ Code along - still needs work [on both PRs](https://github.com/foundersandcoders/pg-walkthrough/pulls). We need to discuss very seriously tomorrow who is going to take this.
+ Error handling - needs another reviewer on the existing PRs & I'll review the error handling tomorrow
+ Morning challenge :+1:
