### ISSUE TITLE
Week 2 - Tweak Eoin's Todo Project

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/master-reference#310]
We're switching from Stopwatch to Todo project.

@finnhodgkin:
- [x] Separate testable logic and dom manipulation into different files (so Tape doesn't throw errors)
- [x] Add a test skeleton file

@oliverjam:
- [x] Clean up some of the comments/instructions
- [x] Rewrite readme to have proper user stories

**Comment by jsms90** [comment]
@oliverjam @finnhodgkin I've just edited the top comment to clarify who you have said is responsible for each part :+1:

**Comment by finnhodgkin** [comment]
@jsms90 Is there a place for us to store the old project.md? I'm moving the new project readme plus skeleton files to a folder in week-2.

**Comment by jsms90** [comment]
Could you move the stopwatch project into `fragments`, like where Eoin's todo app currently is: https://github.com/foundersandcoders/master-reference/tree/master/coursebook/fragments

And then move Eoin's todo app from `fragments` into `week-2/project.md`?

Please use `git mv <old file path> <new file path>`, so that the history is tracked & git doesn't treat it as one file being deleted and then a totally new file being written :+1:

**Comment by finnhodgkin** [comment]
My changes are in the week-2-project branch.

I won't bother making a PR until @oliverjam has added his own changes to the branch.

**Comment by jsms90** [comment]
@finnhodgkin Had a look at your branch :+1: 

Could you please also update the 2 project links in the `week-schedule.md` so they point to the to-do app readme, rather than the stopwatch file

Could you change the name `week-2-stopwatch-project.md`, so that it doesn't reference a specific week number? Also, it's already in the "projects" folder, so maybe just `testing-stopwatch.md`?

**Comment by finnhodgkin** [comment]
@jsms90 I was planning to update the whole of the schedule once @oliverjam and I had moved our new materials to F&C but makes sense to do it iteratively. :+1:

Done

**Comment by jsms90** [comment]
Yep. Everything granular. Each branch should be a feature. You don't want to update based on files. You want to update based on features :+1:

**Comment by oliverjam** [comment]
@jsms90 All done. I'm making a PR for this branch now
