### ISSUE TITLE
 Week 1 - Proposal for changes

### ISSUE THREAD

**Issue by Samatar26** [foundersandcoders/master-reference#311]
**By the end of Sunday 25th June**
- [x] Update week's schedule readme to reflect the week's proposed structure
#333 #338 #367 
- [x] Detail the learning outcomes for the week. #341 
- [x] Detail the Learning outcomes for the accessibility morning challenge. #342
- [x] Change the accessibility challenge to have more of a focus on accessibility, rather than tab-index. #292  See pull request [here](https://github.com/foundersandcoders/accessibility-challenge/pull/6) - @Samatar26 to chase up on getting this merged
- I've updated the solutions branch to have a solution consisting of no tab-indexes. The mentor originally pointed out that he only wanted to point to the existence of tab-index, which is why I believe it should be kept in the original exercise, but that students should understand the page's default behaviour which is tabbing to interactive elements, i.e. links and buttons.

- [x] change the git workshop to a workshop based on two people working on one project #286 
- This answers both the concerns of FACN1 and FAC10, as students will be working on a project (website) and it will be team-based allowing students to experience this before working on their first project.
- [x] The project description needs to be updated to reflect the changes to this workshop and to make clear the workflow is to be follwed by the teams of four instead of the pairs (the pairs merge each other pair PR). #343
- [x] Change the FAC10 research command line readme to a resource/talk. #344
- [x] Replace the git research topic with a research topic on readme #374  
- [ ] Update the CSS gallery challenge to have more of a focus on responsive design https://github.com/foundersandcoders/css-gallery-challenge/issues/5
- Students should be taught about the importance of the meta viewport tag in the challenge

**Comment by jsms90** [comment]
@antoniotrkdz @Samatar26 Don't forget to divide the tasks between you and assign your backlog of issues accordingly.

As @bradreeder mentioned during curriculum planning week, the most effective weeks are those which are planned with the learning outcomes in mind. So @Samatar26, I suggest that you start there
(DWYL always leaves its `priority-1` label for emergencies, so I have assigned `priority-21 to your learning outcomes issue).

**Comment by jsms90** [comment]
@Samatar26 @antoniotrkdz Where are you at with https://github.com/foundersandcoders/css-gallery-challenge/issues/5 ?
