### ISSUE TITLE
3 week project - document/prepare resources that can be used across campuses

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#579]
What's the best way of turning the current content of [week 10](https://github.com/foundersandcoders/master-reference/tree/master/coursebook/weeks-10-12/design-sprint) & [weeks 11-12](https://github.com/foundersandcoders/master-reference/tree/master/coursebook/weeks-10-12/build-sprint ) into something that can be picked up by Nazareth and Gaza?
+ Updating the files for the workshops
+ Creating a `mentor-notes` file/folder
+ Video-ing the delivery in London

---

I'm taking what currently exists on dropbox and making PRs to github based on what the mentors deliver to FAC11, so that it can be iterated on for the other campuses & future iterations

To do:
+ [x] add `mentor-notes` folder with link to Week 10 presentation slides & breakdown of which slides are to be displayed when
+ [x] update material for day 1 #604 
+ [x] update material for day 2 #606 
+ [x] update material for day 3 #607 
+ [x] update material for day 4 #608 
+ [x] update material for day 5 #611
