### ISSUE TITLE
create schedule for build sprint of internal project

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#615]
Schedule timings for the following:
#### Specific to build sprint
+ [x] Introduction to the concept of Agile ceremonies & the Scrum Master role (5-6pm on day 5 of design sprint) #582 
+ [x] Talk on workflow #581 
+ [x] create clearer timings for user testing on penultimate day
+ [x] Agile ceremonies #582
  + sprint planning
  + daily stand-ups
  + sprint review (including demo)
  + team retrospective
  + planning for next sprint 
+ [x] "Today I Learned" (end of first week of build sprint) #614 
+ [x] Add creation of case studies #613 

#### Generic FAC curriculum time slots
+ [x] Introduce the week(s) i.e. learning outcomes & schedule (first 15 mins of day 1)
+ [x] Business development
+ [x] Mentor preparation #558 
+ [x] Day 3 & 5 speaker slots
+ [x] Weekly SGC
