### ISSUE TITLE
Week 1 - Toolkit (cohort feedback)

### ISSUE THREAD

**Issue by mantagen** [foundersandcoders/master-reference#628]
## [Week schedule](https://github.com/foundersandcoders/master-reference/tree/master/coursebook/week-1)

---

#### Schedule
Day 1:
+ [x] add "course overview" talk to day 1 - explain the overview of what gets taught in weeks 1-8 and then weeks 10-16 (#565) #656
+ [x] remove consensus based decision making talk - move into biz dev time as something more interactive (following what @rebeccaradding did in Nazareth) #656
+ [x] move pair programming back into the afternoon, where consensus talk is now, in order to give enough time for course overview talk in the morning #656

Day 2:
+ [x] remove 15 mins "introduce research topics" - move to after lunch #656

Day 5:
+ [x] add 15 minute introduction on "How to code review" #402 #656 #650 
+ [x] move presentation prep right before presentations #403 #656
+ [x] move cohort SGC after presentations #656

#### Pair programming
+ [x] specify 8 kyu for pair programming #653
+ [x] add learning outcomes - to ensure that emphasis is put on learning to pair, rather than completing the kata #652 

#### Accessibility workshop
+ [x] ensure that introduction to accessibility workshop emphasises its importance (add content from [Alastair Duggin's talk](https://drive.google.com/file/d/0Bz6b5hVobZVnZk5VSW1ZWldoSURzSm9uODF6TWxPRDhndWtz/view?usp=sharing)?) #669
+ [ ] video the talk if it gets done in London again

#### Accessibility morning challenge
+ [x] move solution from branch to folder foundersandcoders/accessibility-challenge#19
+ [ ] clarity around tabindex #292 https://github.com/foundersandcoders/accessibility-challenge/issues/5 https://github.com/foundersandcoders/accessibility-challenge/issues/11

#### Git workshop
+ [ ] clarify that we use github flow https://github.com/foundersandcoders/git-workflow-workshop-for-two/issues/38
+ [ ] add diagrams to help understanding of workflow https://github.com/foundersandcoders/git-workflow-workshop-for-two/issues/39

#### Research topics

Still trying to figure out what to do with research afternoon. Should we keep the concept, but change some of the topics?

+ Want to keep mobile-first design. (Note: [suggestion from @antoniotrkdz to add this to the CSS Gallery Challenge](https://github.com/foundersandcoders/css-gallery-challenge/issues/5))
+ Maybe introduce students to dev tools #529 
+ Maybe add "the art of googling" #307 

#### CSS Gallery challenge
+ [ ] make jump between steps in CSS gallery challenge smaller #683 

#### Introduce projects
+ [x] create screencast - walking students through creating a repo together (add readme & gitignore) #681 
+ [x] show students pomodoro timer #592 

---

## Participants
[Gitter channel](https://gitter.im/foundersandcoders/toolkit-week-planning)

Week facilitator: @jsms90 
FACG2: @mrm7moud @abdhalees 
FACN2: @veredrec 
FAC11: @Jen-Harris @rinoma 

## Material for review
Open issues that relate to your week
[Week 1 issues](https://github.com/foundersandcoders/master-reference/issues?q=is%3Aopen+is%3Aissue+label%3Aweek-toolkit)

#### Retrospectives
+ [FAC11 students](https://github.com/foundersandcoders/london-programme/blob/master/stop-go-continue/fac-11/cohort-week-1.md)
+ FAC11 mentors - hadn't started mentor retrospectives yet. Problems that were noticed in the classroom were all raised as [issues](https://github.com/foundersandcoders/master-reference/issues?q=is%3Aopen+is%3Aissue+label%3Aweek-toolkit)
+ [FACN2 students](https://github.com/foundersandcoders/nazareth-programme/blob/master/stop-go-continue/facn2/week1.md)
+ [FACG2 students](https://github.com/foundersandcoders/gaza-programme/blob/master/stop-go-continue/FACG2/2017-07-13.md)

Historical:
+ [FAC10 students](https://github.com/foundersandcoders/london-programme/blob/master/stop-go-continue/fac-10/cohort-week-1.md)
+ [FAC10 mentors](https://github.com/foundersandcoders/london-programme/blob/master/stop-go-continue/fac-10/mentor-week-1.md)
+ [FAC9 students](https://foundersandcoders.gitbooks.io/fac9/content/week1/stop_go_continue.html)
+ [FACN1 students](https://github.com/foundersandcoders/nazareth-curriculum/blob/master/stop-go-continue/fac-n1/week1.md)

**Comment by mrm7moud** [comment]
Related to what was mentioned in [SGC](https://github.com/foundersandcoders/gaza-programme/blob/master/stop-go-continue/FACG2/2017-07-13.md) and what we observed when working on projects, students still struggle with git commands and GitHub for several weeks after week 1, so @abdhalees and I think that the workshop for git and GitHub are not enough.

1- We think that the commands are clear but the using of GitHub is not. e.g. what is the master branch? what are branches used for? how to mention pull requests to issues? issues and when to close? 
So maybe we could add these questions to the workshop. In FACG2, Elias explained them at the end of the week.

2- Even after students understood the process well, they were still afraid of writing the commands especially when pulling from the master and when pushing to a branch, we think it's because they are afraid to screw up there work or the repo. 
There was a suggested idea to make a workshop or something like a code along that includes screwing up a repo or someone's work and then get it back as it was so the students will know that it's always possible to get back to where ever they want. 
We suggest it to be at the end of the week after projects so they can experience it first before knowing the right way.

**Comment by Heathercoraje** [comment]
Reviewers: @veredrec @heathercoraje

### week1
#### Pair programming
when first introduced to pair programming, mentors can explain more about the idea and purpose of pair programming. We suggest that mentors encourage students to choose from easy task (8kyu kata from Codewars) to make sure that they fully understand that the emphasis of this workshop is on pair programming rather than the challenenge itself

#### Accessibility Workshop / Accessibility morning challenge 
We have a similar opinion on the workshop that it is a nice opportunity to be exposed to the topic of `Accessibility`.
By the way, solution file is empty.

#### Git workshop
We think a number of workshop related to Github is fine. 
The only way to actually get familiar with git workflow is by using git commands while working on a project repetitively. We agree with @mrm7moud @abdhalees in that codealong to show students how to get back after screwing their codes could benefit student to feel more comfortable with git workflow.
 
#### Reseach Afternoon
We think that among four topics, CSS and Command Line are essential but we are not sure about Accessibility and Regex. There can be more important and relevant topics to be introduced which can be used frequently later in the course. For example, ATOM and ATOM Packages and dev too. 

#### CSS Gallery Challenge
We think that this workshop is brilliant in particular how the workshop repo shows the result after completeing the task visually.

**Comment by Jen-Harris** [comment]
# London 
reviewers: @rinoma & @jen-harris

Great feedback  @veredrec @Heathercoraje @mrm7moud @abdhalees a lot of our your points so have only written additional ideas: 

**Course Overview**
This is super important and really sets the tone for the following 8 weeks. It may be worth considering taking 11:40-1pm and talking about consensus based decision making during the research time. Also because the introduction game can easily overrun and day 1 is already quite full on! Where possible it would be great for @sofer to be involved in this 

**Biz dev time**
We think it's important to continue using this time as the 'treasure hunt' challenge to explore the github repos as it allows students time to get more familiar with FAC & Github. 

**Pomodoro Timer**
We've spoken a lot in London about introducing the pomodoro timer more formally in week 1 to encourage breaks and efficient working. It might be ideal to introduce and use this in Wednesday afternoo during project time as a whole cohort and then allow students to choose whether then continue using it in following weeks. 
We could also use this introductory time to talk about 20:20:20 and the 'art of googling' .

**Git**
Teach what gitignore is in this time!

**Code Review**
There should be a 15 minute introduction to what code reviewing is and how best to do it to make the most of this time over the following weeks. Also to introduce the concept of alumni reviewing code each week as well.

**Comment by jsms90** [comment]
#### Feedback from the curriculum working group

Approval for most suggestions. 2 things left to consider:
- research afternoon
  - suggestion from @sofer to remove research afternoon altogether and move up the start of the project
  - since there are a few things we would like to keep or add in to this slot (dev tools, how to research), working group suggests that we continue to brainstorm together on this
  - I've added a suggestion in to the existing issue on research afternoons
- working group not comfortable with the idea of learning git through a code along
  - suggestion is to look at improving the existing workshop

**Comment by jsms90** [comment]
@rinoma have you created an issue on the CSS gallery challenge?
