### ISSUE TITLE
Proposals for Intro WS changes

### ISSUE THREAD

**Issue by ameliejyc** [foundersandcoders/master-reference#664]
By the end of Monday 9th October.

## WS - Intro

- [x] Add examples to help differentiate between GET/POST methods.
- [x] include an introduction to AJAX( because it is not introduced);
- [x] include how xhr requests handle redirect responses.
- [x] Brief introduction at the beginning of the workshop --> including the useful learning outcomes the students will get from the workshop. 
- [x] Mentors should go through each section with the group at some time intervals.

Relates #630

**Comment by ameliejyc** [comment]
PR for this: https://github.com/foundersandcoders/api-workshop/pull/22
