### ISSUE TITLE
Week 1 - Curriculum Planning

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/master-reference#822]
# Week 1 - Toolkit + Accessibility

## Intro & Process

Hi, مرحبا  :wave:

See the recommend changes for this week below.

If you are the first here, it's probably a good idea to set up a gitter chat with the name `spring2018-week1-cp` and add it to the link below. Use this to communicate with anyone else working on the week in the different campuses.

[Gitter Channel (currently a dead link)]()

To work on one of the changes, please follow the steps below
  1. Choose an issue no one else has put their github handle next to.
  2. If there is no relevant issue, create one in the relevant repo (likely to be either master reference or a workshop repo) :pencil:
  3. Assign yourself to the relevent issue :raising_hand:
  4. In **this** issue, link to any new issues made next to a change, and **@ yourself so that everyone knows you are going to work on it**. You can of course collabarate with others!
  5. Do the work (on a new branch) :construction_worker: :evergreen_tree:
  6. Open a PR.
     - Add a description explaining what you've done, linking back to the issues (including this one)
     - For reviewers, add anyone who you think might be relevent (workshop creator, interested cohort members) - don't worry if you can't think of anyone!
     - For the assignment, assign the master reference maintainers (@m4v15 and @eliascodes)
  7. Fix any issues that come up :construction: Re-assign or @ people so they know you've done it.
  8. :shipit: Once merged, check the checkbox next to the change (below) :ballot_box_with_check:
  9. Lean back and bask in the warm glow of knowing that today, you made the world a better place :palm_tree: :relaxed: :cake:

  شكرا لك, thank you!

## Timeline
The deadline for all changes for weeks 1-4 is the end of 23rd February. All pull requests must be opened by then. This is so that mentors have stable resources from which to prepare for their weeks. Changes and PRs submitted after this date will not be merged until the corresponding week has been taught in all campuses.

**Note:**
These are our recommendations for this week based on your feedback. None of these changes are mandatory. If you wish to improve the resources and the Founders and Coders course, then it is your collective responsibility to make these changes happen. If some of these recommendations are not achieved in time, that's OK.

---

### General
* [ ] Find some time in the schedule to discuss what makes good presentations, with more specific guidance on what makes a good research presentation and what makes a good project presentation

### Research Topics
* [ ] Change "Command Line" research topics to something more relevant and useful like aliases, editing bash profile, finding and changing file permissions (using `chmod` and/or `chown`)

### CSS Gallery challenge
* [ ] Move solutions and hints from branches to a new directory on `master` branch

### Scavenger Hunt
* [ ] Campus-specific scavenger hunts have dates on them that should be updated
* [ ] Propose an improvement (in the form of an issue) on how to improve the scavenger hunt experience while keeping the following elements
  * Gain a familiarity with where **course**-related resources are located and how they are structured
  * Gain a familiarity with where **campus**-related resources are located and how they are structured
  * Gain an understanding of the nature of FAC International
  * Get better at navigating through github

### Project
* [ ] Add instruction to install and use prettier editor plugin to week 1 project
  * foundersandcoders/master-reference#758

### Git workflow workshop for two
* [ ] Add diagram of various git scenarios to the [git-workflow-workshop-for-two](https://github.com/foundersandcoders/git-workflow-workshop-for-two)
  * For example, pushing a branch, merging a PR, pulling changes, etc.
  * You can use [draw.io]() or any other vector image software you like

* [ ] Add bullet-point summary of the steps to the repo for people to come back to
  * foundersandcoders/git-workflow-workshop-for-two#42

**Comment by eliascodes** [comment]
I've updated the list with another minor fix which was raised today in #846
