### ISSUE TITLE
Week 2 - Curriculum Planning

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/master-reference#823]
# Week 2 - Testing

## Intro & Process

Hi, مرحبا  :wave:

See the recommend changes for this week below.

If you are the first here, it's probably a good idea to set up a gitter chat with the name `spring2018-week2-cp` and add it to the link below. Use this to communicate with anyone else working on the week in the different campuses.

[Gitter Channel (currently a dead link)]()

To work on one of the changes, please follow the steps below
  1. Choose an issue no one else has put their github handle next to.
  2. If there is no relevant issue, create one in the relevant repo (likely to be either master reference or a workshop repo) :pencil:
  3. Assign yourself to the relevent issue :raising_hand:
  4. In **this** issue, link to any new issues made next to a change, and **@ yourself so that everyone knows you are going to work on it**. You can of course collabarate with others!
  5. Do the work (on a new branch) :construction_worker: :evergreen_tree:
  6. Open a PR.
     - Add a description explaining what you've done, linking back to the issues (including this one)
     - For reviewers, add anyone who you think might be relevent (workshop creator, interested cohort members) - don't worry if you can't think of anyone!
     - For the assignment, assign the master reference maintainers (@m4v15 and @eliascodes)
  7. Fix any issues that come up :construction: Re-assign or @ people so they know you've done it.
  8. :shipit: Once merged, check the checkbox next to the change (below) :ballot_box_with_check:
  9. Lean back and bask in the warm glow of knowing that today, you made the world a better place :palm_tree: :relaxed: :cake:

  شكرا لك, thank you!

## Timeline
The deadline for all changes for weeks 1-4 is the end of 23rd February. All pull requests must be opened by then. This is so that mentors have stable resources from which to prepare for their weeks. Changes and PRs submitted after this date will not be merged until the corresponding week has been taught in all campuses.

**Note:**
These are our recommendations for this week based on your feedback. None of these changes are mandatory. If you wish to improve the resources and the Founders and Coders course, then it is your collective responsibility to make these changes happen. If some of these recommendations are not achieved in time, that's OK.

---

### General
* [ ] Use the [original fizzbuzz workshop](https://github.com/foundersandcoders/fizzbuzz) instead of the [edited version](https://github.com/AbdullahChaudhry/fizzbuzz). Update the schedule.
  * foundersandcoders/master-reference#741
* [ ] Add an explanation of object identity before the [pure-functions-easy-testing](https://github.com/foundersandcoders/ws-pure-functions-easy-testing) workshop. You can use [this demonstration](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/fragments/object-pass-by-reference.js) if you wish. If you use anything else, please make a record of what you use.
  * foundersandcoders/master-reference#740
* Create a `mentor-notes.md` file in the week-2 directory. Add a header for the event loop video add some questions that mentors may want to ask either during or after the video to test the understanding of students.

### Fizzbuzz
* [ ] Add instruction that students should use the ping-pong pairing method when completing the workshop, and link back to the explanation of different pairing types from week 1

### Object identity resource
* [ ] Add comment at an appropriate place in the resource to explain that why we need deep equality checks when checking for object equality

### ws-pure-functions-easy-testing
* [ ] Add syntax highlighting to the code blocks in the README
* [ ] Simplify example two: remove the closure from `updateDom`. Simply have a function that does the DOM update based on an input parameter and another function that calculates the value of that parameter based on some other logic.

### Project
* [ ] If they wish, people may submit their proposals for simplification of the project skeleton (in the form of a PR). Note, however, that the two major motivations for the skeleton are (1) a separation between the pure and impure parts of the app to make TDD easy, and (2) to have students dive into an unfamiliar code-base. We are keen for both these aspects to remain.
* [ ] Remove `cloneArrayOfObjects` from the project skeleton and the discussion of object identity from the project description
  * foundersandcoders/master-reference#740

**Comment by m4v15** [comment]
Hey all, added a new task to update the resources.md file as flagged up in #847
