### ISSUE TITLE
Week 3 - curriculum planning

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/master-reference#824]
# Week 3 - APIs

## Intro & Process

Hi, مرحبا  :wave:

See the recommend changes for this week below.

If you are the first here, it's probably a good idea to set up a gitter chat with the name `spring2018-week3-cp` and add it to the link below. Use this to communicate with anyone else working on the week in the different campuses.

[Gitter Channel (currently a dead link)]()

To work on one of the changes, please follow the steps below
  1. Choose an issue no one else has put their github handle next to.
  2. If there is no relevant issue, create one in the relevant repo (likely to be either master reference or a workshop repo) :pencil:
  3. Assign yourself to the relevent issue :raising_hand:
  4. In **this** issue, link to any new issues made next to a change, and **@ yourself so that everyone knows you are going to work on it**. You can of course collabarate with others!
  5. Do the work (on a new branch) :construction_worker: :evergreen_tree:
  6. Open a PR.
     - Add a description explaining what you've done, linking back to the issues (including this one)
     - For reviewers, add anyone who you think might be relevent (workshop creator, interested cohort members) - don't worry if you can't think of anyone!
     - For the assignment, assign the master reference maintainers (@m4v15 and @eliascodes)
  7. Fix any issues that come up :construction: Re-assign or @ people so they know you've done it.
  8. :shipit: Once merged, check the checkbox next to the change (below) :ballot_box_with_check:
  9. Lean back and bask in the warm glow of knowing that today, you made the world a better place :palm_tree: :relaxed: :cake:

  شكرا لك, thank you!

## Timeline
The deadline for all changes for weeks 1-4 is the end of 23rd February. All pull requests must be opened by then. This is so that mentors have stable resources from which to prepare for their weeks. Changes and PRs submitted after this date will not be merged until the corresponding week has been taught in all campuses.

**Note:**
These are our recommendations for this week based on your feedback. None of these changes are mandatory. If you wish to improve the resources and the Founders and Coders course, then it is your collective responsibility to make these changes happen. If some of these recommendations are not achieved in time, that's OK.

---

### General
* [ ] Replace parallel morning challenge with [waterfall morning challenge](https://github.com/foundersandcoders/mc-waterfall-chaser)
* [ ] Move parallel morning challenge to its own repo

### mc-waterfall-chaser
* [ ] Add simple diagram of parallel vs series async operations to give more context

### api-workshop
* [ ] Fix inaccuracies in descriptions
  * foundersandcoders/api-workshop#30
  * foundersandcoders/api-workshop#31
  * foundersandcoders/api-workshop#32
* [ ] Try to reduce the amount of block-text, possibly by adding diagrams or tables
  * For example, HTTP methods and/or status codes might be better displayed in tabular form (see MDN for example)
  * The massive quote at the beginning of the XHR section can be moved to the end. Instead a very short motivation on XHR and its purpose

### workshop-APIs
* [ ] Use actual `Error` object instead of string on line 68 of solution
* [ ] Simplify solution. Our suggestions are below, but happy to consider others:
  * Don't hardcode the control flow in the function definitions: instead simply have serially nested callbacks in the top-level call
  * Improve variable and function names (e.g. "obj", "json", etc)
  * foundersandcoders/master-reference#766
