### ISSUE TITLE
Week 5 - Curriculum Planning

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/master-reference#826]
# Week 5 - Node II

## Recommended Changes

Hi, مرحبا  :wave: 

See the recommend changes for this week below. 

If you are the first here, it's probably a good idea to set up a gitter chat with the name `spring2018-week5-cp` and add it to the link below. Use this to communicate with anyone else working on the week in the different campuses.

[Gitter Channel (currently a dead link)]()

To work on one of the changes, please follow the steps below:
  1. Choose an issue no one else has put their github handle next to. 
  2. If there is no relevant issue, create one in the relevant repo (likely to be either master reference or a workshop repo) :pencil: 
  3. Assign yourself to the relevent issue :raising_hand: 
  4. In **this** issue, link to any new issues made next to a change, and **@ yourself so that everyone knows you are going to work on it**. You can of course collabarate with others!
  5. Do the work (on a new branch) :construction_worker: :evergreen_tree: 
  6. Open a PR.
     - Add a description explaining what you've done, linking back to the issues (including this one)
     - For reviewers, add anyone who you think might be relevent (workshop creator, interested cohort members) - don't worry if you can't think of anyone! `n.b. we can maybe lose this bit and we could add reviewers of people we know who could look at it`
     - For the assignment, assign the master reference maintainers (@m4v15 and @eliascodes)
  7. Fix any issues that come up :construction: Re-assign or @ people so they know you've done it.
  8. :shipit: Once merged, check the checkbox next to the change (below) :ballot_box_with_check:
  9. Lean back and bask in the warm glow of knowing that today, you made the world a better place :palm_tree: :relaxed: :cake:
  
  شكرا لك, thank you!

## Timeline
The deadline for all changes for weeks 5-8 is the end of 23rd March. All pull requests must be opened by then. This is so that mentors have stable resources from which to prepare for their weeks. Changes and PRs submitted after this date will not be merged until the corresponding week has been taught in all campuses.

**Note:**
These are our recommendations for this week based on your feedback. None of these changes are mandatory. If you wish to improve the resources and the Founders and Coders course, then it is your collective responsibility to make these changes happen. If some of these recommendations are not achieved in time, that's OK.

---
#### General

- [ ] Create slides.md and add new resource to it 
  - foundersandcoders/master-reference#772
##### Error Handling WS
- [ ] Add a test on edge case
  - foundersandcoders/error-handling-workshop#32
- [ ] Re-order so that async error handling comes first, then throwing, then returning (latter possibly as an extra). Put the general principles section after exercises
  - foundersandcoders/error-handling-workshop#33
- [ ] Try to generally improve the explanations. If current students need some help with it, would advise asking alumni, doing some research, or shout out on FAC gitter channel. Use of diagrams might help.

##### Request Module MC
- [ ] Add logging to differentiate results of request module from results of myRequest module
  - RhodesPeter/request-module-workshop#5

##### Project
- [ ] Add better explanation of project requirement - the term _"feed"_ added confusion and led people to believe it should update in realtime
  - foundersandcoders/master-reference#790

##### Research
- [ ] Clarify wording in buffers/streams topic, input should determine the chunk size 
  - foundersandcoders/master-reference#780

##### TDD Node server with shot WS
- [ ] Replace shot with supertest 
  - foundersandcoders/tdd-node-server-with-shot-and-tape#34

**Comment by polyccon** [comment]
Apart from the projects requirements and the edge case test, is this all necessary? The week was massively improved for FAC12 thanks to @eliascodes 's hard work, as well as @finnhodgkin in reshaping the workshops.

**Comment by eliascodes** [comment]
@polyccon as it says above in the note:

> None of these changes are mandatory

These are the recommendations we made based on feedback from all campuses, and we believe they will improve the outcomes for the week. Taken individually, none of the recommendations here are particularly substantial.

**Comment by astroash** [comment]
☝️ edited request module link
