### ISSUE TITLE
Week 7 - Curriculum Planning

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/master-reference#828]
# Week 7 - Auth Week

## Recommended Changes

Hi, مرحبا  :wave: 

See the recommend changes for this week below. 

If you are the first here, it's probably a good idea to set up a gitter chat with the name `spring2018-week7-cp` and add it to the link below. Use this to communicate with anyone else working on the week in the different campuses.

[Gitter Channel (currently a dead link)]()

To work on one of the changes, please follow the steps below:
  1. Choose an issue no one else has put their github handle next to. 
  2. If there is no relevant issue, create one in the relevant repo (likely to be either master reference or a workshop repo) :pencil: 
  3. Assign yourself to the relevent issue :raising_hand: 
  4. In **this** issue, link to any new issues made next to a change, and **@ yourself so that everyone knows you are going to work on it**. You can of course collabarate with others!
  5. Do the work (on a new branch) :construction_worker: :evergreen_tree: 
  6. Open a PR.
     - Add a description explaining what you've done, linking back to the issues (including this one)
     - For reviewers, add anyone who you think might be relevent (workshop creator, interested cohort members) - don't worry if you can't think of anyone! 
     - For the assignment, assign the master reference maintainers (@m4v15 and @eliascodes)
  7. Fix any issues that come up :construction: Re-assign or @ people so they know you've done it.
  8. :shipit: Once merged, check the checkbox next to the change (below) :ballot_box_with_check:
  9. Lean back and bask in the warm glow of knowing that today, you made the world a better place :palm_tree: :relaxed: :cake:
  
  شكرا لك, thank you!

## Timeline
The deadline for all changes for weeks 5-8 is the end of 23rd March. All pull requests must be opened by then. This is so that mentors have stable resources from which to prepare for their weeks. Changes and PRs submitted after this date will not be merged until the corresponding week has been taught in all campuses.

**Note:**
These are our recommendations for this week based on your feedback. None of these changes are mandatory. If you wish to improve the resources and the Founders and Coders course, then it is your collective responsibility to make these changes happen. If some of these recommendations are not achieved in time, that's OK.

---
#### General

- [ ] Rename ws-session-management to ws-jwt-stateless-session or something else more accurate

##### Cookies WS/Session management WS
- [ ] Add very brief framing section to ws-session-managemet on stateful vs stateless sessions and why JWT; do not cover too much that would fall into research afternoon.

##### Client Side Validation MC
- [ ] Add solution from branch to folder, and generally clean it up
- [ ] Clarify the instructions 
  - HTML5 _validation_ is allowed, but **do not** use the default styling - must be custom styled. 
  - Can link to [relevant MDN docs](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation), makes the JS part of the workshop more incidental.
  - Rephrase _"don't use inline HTML handlers"_ -> _"if using event listeners, attach event listeners in JS, not directly in HTML with `on<event>`"_
##### Promise me this MC
- [ ] Fix the typo 
  - foundersandcoders/mc-promise-me-this#9

##### Project
- [ ] Update the project description to allow the CF/mentors the freedom to choose to make this project an extension of the previous weeks.  
  - foundersandcoders/master-reference#764
