### ISSUE TITLE
Week 8 - Curriculum Planning

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/master-reference#829]
# Week 8 - Express, Handlebars

## Recommended Changes

Hi, مرحبا  :wave: 

See the recommend changes for this week below. 

If you are the first here, it's probably a good idea to set up a gitter chat with the name `spring2018-week8-cp` and add it to the link below. Use this to communicate with anyone else working on the week in the different campuses.

[Gitter Channel (currently a dead link)]()

To work on one of the changes, please follow the steps below:
  1. Choose an issue no one else has put their github handle next to. 
  2. If there is no relevant issue, create one in the relevant repo (likely to be either master reference or a workshop repo) :pencil: 
  3. Assign yourself to the relevent issue :raising_hand: 
  4. In **this** issue, link to any new issues made next to a change, and **@ yourself so that everyone knows you are going to work on it**. You can of course collabarate with others!
  5. Do the work (on a new branch) :construction_worker: :evergreen_tree: 
  6. Open a PR.
     - Add a description explaining what you've done, linking back to the issues (including this one)
     - For reviewers, add anyone who you think might be relevent (workshop creator, interested cohort members) - don't worry if you can't think of anyone!
     - For the assignment, assign the master reference maintainers (@m4v15 and @eliascodes)
  7. Fix any issues that come up :construction: Re-assign or @ people so they know you've done it.
  8. :shipit: Once merged, check the checkbox next to the change (below) :ballot_box_with_check:
  9. Lean back and bask in the warm glow of knowing that today, you made the world a better place :palm_tree: :relaxed: :cake:
  
  شكرا لك, thank you!

## Timeline
The deadline for all changes for weeks 5-8 is the end of 23rd March. All pull requests must be opened by then. This is so that mentors have stable resources from which to prepare for their weeks. Changes and PRs submitted after this date will not be merged until the corresponding week has been taught in all campuses.

**Note:**
These are our recommendations for this week based on your feedback. None of these changes are mandatory. If you wish to improve the resources and the Founders and Coders course, then it is your collective responsibility to make these changes happen. If some of these recommendations are not achieved in time, that's OK.

---
#### General
- [ ] Switch the handlebars and testing workshops (to get one full day of express) 
  - foundersandcoders/master-reference#797
- [ ] Remove duplicated "introduce research topics" from week 8 schedule

#### Express WS
- [ ] Remove unnecessary use of JSON body parser 
  - foundersandcoders/express-workshop#14
- [ ] Switch order of steps 
  - foundersandcoders/express-workshop#15

#### Express Testing WS
- [ ] Change _"test"/"tape"_ typo
  - foundersandcoders/express-and-testing-workshop#23
- [ ] Remove database from workshop (substitute with in-memory data-store). Potentially needs guidance. [This Issue](https://github.com/foundersandcoders/express-and-testing-workshop/issues/25) is somewhat relevant and a PR is open to add instructions for linux users. However, this workshop doesn't really _need_ a complicated DB set up so it will probably be better of if it can be replaced with some sort of basic data store (e.g. just a simple object that has the data). Will require rewriting all the queries and db-build stuff.
  - foundersandcoders/express-and-testing-workshop#14
  - foundersandcoders/express-and-testing-workshop#25
  - foundersandcoders/express-and-testing-workshop#26
- [ ] Add some brief info about how this is effectively integration testing/what integration testing is (refer back to weeks 2 & 5) 
  - foundersandcoders/express-and-testing-workshop#24

#### Express Handlebars WS
- [ ] Halve the number of fruit files, or find a way to make the refactoring of it to make it less repetitive. 
  - foundersandcoders/express-handlebars-workshop#16
- [ ] Add diagram to illustrate the way layouts, partials and views interact with models and controllers 
  - foundersandcoders/express-handlebars-workshop#15
- [ ] Re-order the workshop. Introduce elements of handlebars (layout, views, partials) separately and in order of their natural hierarchy.
  - foundersandcoders/express-handlebars-workshop#12

#### Project
- [ ] Direct them to research how to do error handling with express in the project docs 
  - foundersandcoders/master-reference#795
