### ISSUE TITLE
Review and update new cohort checklist

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/master-reference#950]
https://github.com/foundersandcoders/master-reference/blob/faeefa255884574fddc5bcb92b46fed42a95c514/curriculum-planning/new-cohort-checklist.md

@arrested-developer @charlielafosse could you please update this as appropriate during your handover?

Also, worth reflecting on whether this checklist is truly relevant to the `master-reference` or if it is London specific.

**Comment by arrested-developer** [comment]
Definitely needs doing, as this isn't entirely in line with current practice

- [ ] remove cohort-github-organisation.md
- [ ] update new-cohort-checklist and include necessary info about creating a cohort github org
- [ ] make sure all steps are relevant to any campus
